projects:
  MVPfanpage-staging:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: ap-northeast-2
        apiId: 66pokb7lqffjhhtjrzerlwhdzq
        maxDepth: 2
extensions:
  amplify:
    version: 3
